baseURL = 'https://pagyp.github.io/'
languageCode = 'en-us'
title = 'https://blog.paginton.cloud'
theme = "ananke"
SectionPagesMenu = "main"


[params]
  author = "Paul Paginton"
  show_reading_time = true
  Description = "A blog about cloud, with a bias toward Azure, cloud networking, security and Infrastructure as Code and other things that interest me"
  
  
  
  



[[params.ananke_socials]]
name = "rss"
url = "https://blog.paginton.cloud/index.xml"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/pagyp"

[[params.ananke_socials]]
name = "mastodon"
url = "https://infosec.exchange/@paul_paginton"
rel = "me"


canonifyURLs = true


    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
