baseURL = 'https://pagyp.github.io/'
languageCode = 'en-us'
title = 'https://blog.paginton.cloud'
theme = "ananke"
SectionPagesMenu = "main"


[params]
  author = "Paul Paginton"
  show_reading_time = true
  
  
  
  



[[params.ananke_socials]]
name = "rss"
url = "https://blog.paginton.cloud/index.xml"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/pagyp"

[[params.ananke_socials]]
name = "mastodon"
url = "https://infosec.exchange/@paul_paginton"
rel = "me"


canonifyURLs = true


